Repository onebeyond/spdx-license-satisfies, pull requests merged in 2023-10, with the labels that each got.

#11 feat: add husky hooks
  .husky/commit-msg
  .husky/pre-commit
  .husky/pre-push
  .nvmrc
  commitlint.config.js
  package-lock.json
  package.json
  test/cases.js
Labels: enhancement

#16 feat: add gh actions to create draft releases with new changes
  .github/release-drafter.yml
  .github/workflows/label-checker.yml
  .github/workflows/publish.yml
  .github/workflows/release-and-publish.yml
  .github/workflows/release-drafter.yml
  .github/workflows/semantic-pull-request.yml
Labels: enhancement, minor

#15 fix: prepare script
  package.json
Labels: patch

#17 docs: add badges to readme file
  README.md
Labels: major

#18 fix: typo in npm org name
  package-lock.json
  package.json
Labels: patch

#19 chore: force the tag and version for the first release
  .github/workflows/release-drafter.yml
Labels: patch
